set nobackup
set noswapfile
set nowritebackup
set scrolloff=8

inoremap jk <ESC>

colorscheme evening

set tabstop=2
set shiftwidth=2
set expandtab
set timeoutlen=100

syntax enable

set number

set fillchars=eob:\ 
highlight EndOfBuffer ctermfg=bg ctermbg=bg

set clipboard=unnamedplus

let &t_SI = "\e[6 q" " Insert mode
let &t_EI = "\e[2 q" " Normal mode

set nocompatible

filetype plugin indent on

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4  " Открывать файлы в предыдущем окне
let g:netrw_altv = 1          " Открывать разделение справа
let g:netrw_winsize = 20
nnoremap <C-n> :Lexplore<CR>

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l


nnoremap <silent> > :bnext<CR>
nnoremap <silent> < :bprev<CR>

nnoremap <C-x> :bd<CR>

nnoremap <leader>b :buffer<Space>

set laststatus=2

set nofoldenable
set lazyredraw
set ttyfast
