if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git ~/.config/zsh/zsh-snap
source ~/.config/zsh/zsh-snap/znap.zsh


# znap source marlonrichert/zsh-autocomplete
# znap source ohmyzsh/ohmyzsh
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
znap prompt romkatv/powerlevel10k

HISTFILE=~/.zsh_history
HISTSIZE=300
SAVEHIST=100
setopt appendhistory

autoload -Uz compinit
compinit

# aliases:
alias ls='ls --color=auto'
alias btw='fastfetch'

# vi mode settings:
bindkey -v
export KEYTIMEOUT=10
bindkey -M viins "jk" vi-cmd-mode

function zle-line-init zle-keymap-select {
    case ${KEYMAP} in
        vicmd) echo -ne '\e[2 q';; # block cursor for normal mode
        viins|main) echo -ne '\e[6 q';; # beam cursor for insert mode
    esac
}
zle -N zle-line-init
zle -N zle-keymap-select

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
