[[block]]
block = "memory"
format = " $icon $mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi) ($mem_used_percents.eng(w:3)) "

[[block]]
block = "amd_gpu"
format = " $icon $utilization "
format_alt = " $icon MEM: $vram_used_percents ($vram_used/$vram_total) "
interval = 1

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 5
format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m)|} {$power|} "
charging_format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m)|} {$power|} "
full_format = " $icon $percentage {$power|} "
empty_format = " $icon Empty: $percentage {$power|} "
not_charging_format = " $icon $percentage {$time_remaining.dur(hms:true, min_unit:m)|} {$power|} "

[[block]]
block = "sound"
device_kind = "sink"
show_volume_when_muted = true
headphones_indicator = true
format = " $icon {$volume|} $output_description "

[[block]]
block = "sound"
device_kind = "source"
show_volume_when_muted = true
format = " $icon {$volume|} "

[[block]]
block = "load"
format = " $1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4) "
interval = 1

[[block]]
block = "net"
device = "."
format = " $icon {$ssid ($signal_strength)|Wired} [$device] down:$speed_down.eng(prefix:K) up:$speed_up.eng(prefix:K) $bitrate $ip "

[[block]]
block = "keyboard_layout"
driver = "sway"

[[block]]
block = "time"
interval = 1
[block.format]
full = " $timestamp.datetime(f:'%a %Y-%m-%d %H:%M:%S') "
